# Generated by Django 3.2.9 on 2021-11-11 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pure', '0002_userauth_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='userauth',
            name='forget_password_token',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
