# Generated by Django 3.2.9 on 2021-11-13 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pure', '0005_auto_20211113_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description1',
            field=models.TextField(blank=True, null=True),
        ),
    ]
