# Generated by Django 3.2.9 on 2021-11-15 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pure', '0006_alter_product_description1'),
    ]

    operations = [
        migrations.AddField(
            model_name='userauth',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userauth',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userauth',
            name='phone',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
