# Generated by Django 3.2.9 on 2021-11-15 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pure', '0007_auto_20211115_1809'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userauth',
            old_name='first_name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='userauth',
            old_name='last_name',
            new_name='lastname',
        ),
        migrations.RemoveField(
            model_name='userauth',
            name='phone',
        ),
    ]
