# Generated by Django 4.1.5 on 2023-01-19 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pure', '0010_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
