# Generated by Django 4.1.5 on 2023-01-19 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pure', '0011_remove_profile_name_profile_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='phone',
            new_name='phone_number',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profile_auth_token',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='session_token',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='state',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='username',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='zipcode',
        ),
    ]
