# Generated by Django 4.1.5 on 2023-01-19 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pure', '0012_rename_phone_profile_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='auth_token',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='forget_password_token',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_Verified',
            field=models.BooleanField(default=False),
        ),
    ]
