# Generated by Django 4.1.5 on 2023-02-08 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pure', '0014_delete_userauth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='product_images'),
        ),
    ]
