# Generated by Django 4.1.5 on 2023-02-08 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pure', '0015_alter_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='images',
            field=models.ManyToManyField(to='pure.image'),
        ),
    ]
