# Generated by Django 4.1.5 on 2023-02-08 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pure', '0017_image_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='name',
            field=models.CharField(default='Product Image', max_length=255),
        ),
    ]
