# Generated by Django 4.1.5 on 2023-02-25 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pure', '0019_product_main_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='carousel_image', to='pure.image'),
        ),
    ]
