# Generated by Django 3.2.9 on 2021-11-15 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20211115_0720'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='consignment_number',
            new_name='order_track_number',
        ),
    ]
