# Generated by Django 4.1.5 on 2023-01-19 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pure', '0013_profile_auth_token_profile_forget_password_token_and_more'),
        ('orders', '0008_alter_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pure.profile'),
        ),
    ]
